define(["utils/logger", "utils/observable"], function(Log, Observable) {

    return {
        OK : "OK",

        GET_FAILED_ENTRY_NOT_FOUND            : "GET_FAILED_ENTRY_NOT_FOUND",
        DELETE_FAILED_ENTRY_NOT_FOUND         : "DELETE_FAILED_ENTRY_NOT_FOUND",
        CREATE_FAILED_ENTRY_ALREADY_EXISTS    : "CREATE_FAILED_ENTRY_ALREADY_EXISTS",
        CREATE_FAILED_DUE_TO_OWNERSHIP_CHECK  : "CREATE_FAILED_DUE_TO_OWNERSHIP_CHECK",
        DELETE_FAILED_DUE_TO_OWNERSHIP_CHECK  : "DELETE_FAILED_DUE_TO_OWNERSHIP_CHECK"
    };
});