var Global = {
     OK :       "OK",
     CONNECTED: "CONNECTED",
     FAILED:    "FAILED",

     SEND_TO_ENDPOINT_RECIPIENT_ENDPOINT_CANNOT_BE_FOUND: "SEND_TO_ENDPOINT_RECIPIENT_ENDPOINT_CANNOT_BE_FOUND",

     GET_FAILED_ENTRY_NOT_FOUND            : "GET_FAILED_ENTRY_NOT_FOUND",
     DELETE_FAILED_ENTRY_NOT_FOUND         : "DELETE_FAILED_ENTRY_NOT_FOUND",
     CREATE_FAILED_ENTRY_ALREADY_EXISTS    : "CREATE_FAILED_ENTRY_ALREADY_EXISTS",
     UPDATE_FAILED_DUE_TO_OWNERSHIP_CHECK  : "UPDATE_FAILED_DUE_TO_OWNERSHIP_CHECK",
     DELETE_FAILED_DUE_TO_OWNERSHIP_CHECK  : "DELETE_FAILED_DUE_TO_OWNERSHIP_CHECK",

     CALL_FAILED_UNKNOWN_METHOD       : "CALL_FAILED_UNKNOWN_METHOD",
     CALL_FAILED_UNEXPECTED_EXCEPTION : "CALL_FAILED_UNEXPECTED_EXCEPTION",

     FAILED_DUE_TO_CONNECTION_LOST    : "FAILED_DUE_TO_CONNECTION_LOST",
     REJECTED_BY_TIMEOUT              : "REJECTED_BY_TIMEOUT",

     INSTANCE_DESTROYED: "INSTANCE_DESTROYED"
 }

export {Global}
